# Generated by Django 5.1.3 on 2024-12-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
    ]
